
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
    ports:
      - "5332:5432"
    volumes:
      - db:/data/postgres

volumes:
  db: